### ISSUE TITLE
tune.py

### ISSUE THREAD

**Issue by asd351012** [YuxueYang1204/TrimGS#11]
Why is the point cloud of some of my datasets larger in storage size after being processed by tune.py compared to before the processing?

**Comment by YuxueYang1204** [comment]
Hi, @asd351012 The number of Gaussians is affected by both densification and pruning. You can set `--split scale` to only use the Scale-driven Densification rather than the `mix` mode. Additionally, you can experimentally try lowering the `contribution_prune_interval` or increasing the `densification_interval`. Hope this may help you!

**Comment by asd351012** [comment]
Thank you for your patient explanation. I will give it a try.
