### ISSUE TITLE
I want to know where is the "scale driven" in code

### ISSUE THREAD

**Issue by poorGiser** [YuxueYang1204/TrimGS#4]
![屏幕截图 2024-06-19 114201](https://github.com/YuxueYang1204/TrimGS/assets/129021453/dfc6cad3-4ad8-4734-b371-ab45c3890e56)

**Comment by Abyssaledge** [comment]
Thanks for your attention. Here is the implementation: https://github.com/YuxueYang1204/TrimGS/blob/main/Trim3DGS/tune.py#L251

**Comment by tb2-sy** [comment]
Thanks for your nice work! 
Why do I need to use prune_mask again after dense_and_scale_split in "mix" split mode, but there is no prune_mask after dense_and_scale_split in "scale" mode?

**Comment by YuxueYang1204** [comment]
@tb2-sy Thank you for your kind words!

We set "mix" mode to obtain more Gaussians than in "scale" mode, which facilitates a good representation of geometry details. The difference in using the prune_mask between the "mix" and "scale" modes is due to my mistake. However, based on experimental performance, it doesn't matter if you remove the prune step after dense_and_scale_split in "mix" mode.
